macos_min_version:             # [osx and x86_64]
  - 10.12                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.12                      # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.12                      # [osx and x86_64]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
