{% set name = "pyceres" %}
{% set version = "2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/cvg/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 00bbc4629997809c505669393b3bec97b2aa21ea8feffa2e4e9143dfde8eece5
    patches:
      - fix-cmake.patch
      - fixup-version-number.patch
      - fix-win-build.patch
      - fix-glog-init.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make                                   # [unix]
    - ninja                                  # [win]
    - pip                                    # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config
    - llvm-openmp                    # [osx]
    - libcxx                         # [osx]
    - libgomp                        # [linux]
    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [unix and not arm64]
    - {{ cdt('mesa-dri-drivers') }}  # [unix and not arm64]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
    - sysroot_linux-64 2.17          # [linux64]
  host:
    - pip
    - python
    - pybind11
    - libboost-headers
    - libblas
    - libcblas
    - colmap
    - cgal-cpp
    - ceres-solver
    - eigen
    - numpy
    - glog
    - gflags
    # x11 stuff
    - xorg-libxext                   # [unix]
    - xorg-libxdmcp                  # [unix]
    - xorg-libxau                    # [unix]
    - libxcb                         # [unix]
    - xorg-libxfixes                 # [unix]
    - xorg-libxrender                # [unix]
    - xorg-libx11                    # [unix]
    - xorg-libice                    # [unix]
    - xorg-libsm                     # [unix]
    - libglu                         # [linux]
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible("libcxx") }}  # [osx]

test:
  imports:
    - pyceres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cvg/pyceres
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: pyceres provides minimal Python bindings for the Ceres Solver and the implementation of factor graphs for bundle adjustment and pose graph optimization.

extra:
  recipe-maintainers:
    - Tobias-Fischer
