{% set name = "pyceres" %}
{% set version = "2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/cvg/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 00bbc4629997809c505669393b3bec97b2aa21ea8feffa2e4e9143dfde8eece5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make                                   # [unix]
    - ninja                                  # [win]
    - pip                                    # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scikit-build                           # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - pkg-config
    - sysroot_linux-64 2.17          # [linux64]
  host:
    - pip
    - python
    - pybind11
    - scikit-build
    - scikit-build-core
    - libboost-headers
    - ceres-solver
    - numpy
    - glog
    - gflags
  run:
    - python
    - {{ pin_compatible("numpy") }}

test:
  imports:
    - pyceres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cvg/pyceres
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: pyceres provides minimal Python bindings for the Ceres Solver and the implementation of factor graphs for bundle adjustment and pose graph optimization.

extra:
  recipe-maintainers:
    - Tobias-Fischer
